cognitive_apprenticeship/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('public.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('author/', include('author.urls')),
    path('reviewer/', include('reviewer.urls')),
    path('editor/', include('editor.urls')),
    path('profile/', include('roles.urls')),
    path('test/', include('common.urls')),
]

reviewer/urls.py
from django.urls import path

from . import views

app_name = "reviewer"
urlpatterns = [
    path('', views.ReviewerHome.as_view(), name='home'),
    path('manuscripts/<int:pk>', views.ShowManuscript.as_view(), name='show_manuscript'),
    path('manuscripts/<int:manuscript_pk>/versions/<int:revision_number>', 
            views.ShowRevision.as_view(), name='show_revision'),
    path('manuscripts/<int:manuscript_pk>/versions/<int:revision_number>/reviews', 
            views.ShowReviews.as_view(), name='show_reviews'),
    path('manuscripts/<int:manuscript_pk>/versions/<int:revision_number>/review', 
            views.ShowReview.as_view(), name='show_review'),
    path('manuscripts/<int:manuscript_pk>/versions/<int:revision_number>/review/instructions', 
            views.ReviewInstructions.as_view(), name='review_instructions'),
    path('manuscripts/<int:manuscript_pk>/versions/<int:revision_number>/review/edit', 
            views.EditReview.as_view(), name='edit_review'),
]

roles/urls.py
from django.urls import path
from roles import views

app_name = "roles"
urlpatterns = [
    path('edit', views.EditProfile.as_view(), name="edit"),
    path('password', views.ChangePassword.as_view(), name="password"),
    path('', views.ShowProfile.as_view(), name="detail"),
]

reviewer/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from enum import Enum, auto

class ReviewManager(models.Manager):
    def for_manuscript(self, manuscript):
        return self.get_queryset().filter(revision__manuscript=manuscript)

class Review(models.Model):
    class StatusChoices(models.TextChoices):
        ASSIGNED = 'ASSIGNED', 'Assigned'
        SUBMITTED = 'SUBMITTED', 'Submitted'
        COMPLETE = 'COMPLETE', 'Complete'
        EXPIRED = 'EXPIRED', 'Expired'
        WITHDRAWN = 'WITHDRAWN', 'Manuscript was withdrawn'
        NOT_NEEDED = 'NOT_NEEDED', "A decision was reached before this review was submitted"
        EDIT_REQUESTED = 'EDIT_REQUESTED', 'Editing of review requested'
    class RecommendationChoices(models.TextChoices):
        ACCEPT = 'ACCEPT', 'Accept'
        MINOR_REVISION = 'MINOR', 'Minor revision'
        MAJOR_REVISION = 'MAJOR', 'Major revision'
        REJECT = 'REJECT', 'Reject'
    reviewer = models.ForeignKey(User, on_delete=models.CASCADE, related_name='reviews')
    revision = models.ForeignKey('author.Revision', on_delete=models.CASCADE,
            related_name='reviews')
    text = models.TextField(blank=True, null=True)
    status = models.CharField(max_length=20, choices=StatusChoices.choices, default=StatusChoices.ASSIGNED)
    recommendation = models.CharField(max_length=20,
            choices=RecommendationChoices.choices, blank=True, null=True)
    date_due = models.DateTimeField(blank=True, null=True)
    date_submitted = models.DateTimeField(blank=True, null=True)
    date_closed = models.DateTimeField(blank=True, null=True)
    editor_feedback = models.TextField(blank=True, null=True)

    objects = ReviewManager()

    def __str__(self):
        return 'Review of "{}" v{} assigned to {} ({})'.format(
            self.revision.title,
            self.revision.revision_number,
            self.reviewer.username,
            self.status
        )

    # TODO Delete?
    def is_expired(self):
        return self.status == self.StatusChoices.EXPIRED

    # TODO Delete?
    def is_assigned(self):
        return self.status in [
            self.StatusChoices.ASSIGNED,
            self.StatusChoices.EDIT_REQUESTED,
        ]

    # TODO Delete?
    def is_submitted(self):
        return self.status == self.StatusChoices.SUBMITTED

    def get_absolute_url(self):
        return reverse('reviewer:show_review', 
                args=(self.revision.manuscript_id, self.revision.revision_number))
            
    def can_submit(self):
        return self.status in [
            self.StatusChoices.ASSIGNED,
            self.StatusChoices.EDIT_REQUESTED,
        ]

    class KanbanColumns(Enum):
        ASSIGNED = auto()
        SUBMITTED = auto()
        COMPLETE = auto()
        
    KANBAN_ASSIGNMENT = {
        StatusChoices.ASSIGNED:         KanbanColumns.ASSIGNED,
        StatusChoices.EDIT_REQUESTED:   KanbanColumns.ASSIGNED,
        StatusChoices.WITHDRAWN:        KanbanColumns.COMPLETE,
        StatusChoices.EXPIRED:          KanbanColumns.ASSIGNED,
        StatusChoices.SUBMITTED:        KanbanColumns.SUBMITTED,
        StatusChoices.NOT_NEEDED:       KanbanColumns.COMPLETE,
        StatusChoices.COMPLETE:         KanbanColumns.COMPLETE,
    }

    def kanban_column(self):
        return self.KANBAN_ASSIGNMENT[self.status]

    @classmethod
    def in_kanban_columns(self, reviews):
        return {col: [r for r in reviews if r.kanban_column() == col] for col in self.KanbanColumns}

class ManuscriptReviewer(models.Model):
    manuscript = models.ForeignKey('author.Manuscript', on_delete=models.CASCADE)
    reviewer = models.ForeignKey(User, on_delete=models.CASCADE)

reviewer/forms.py
from django import forms
from tinymce.widgets import TinyMCE
from .models import Review

class EditReviewForm(forms.ModelForm):
    text = forms.CharField(widget=TinyMCE())

    class Meta:
        model = Review
        fields = ['text', 'recommendation']

reviewer/views.py
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.detail import DetailView
from author.models import Manuscript, Revision
from author.mixins import ManuscriptRevisionMixin
from django.urls import reverse
from django.shortcuts import redirect
from django.contrib import messages
from django.http import HttpResponseForbidden
from django.shortcuts import Http404

from .models import Review
from .mixins import ReviewerMixin, RevisionReviewMixin
from .forms import EditReviewForm
from .state_machine import ReviewStateMachine

class ReviewerHome(ReviewerMixin, TemplateView):
    template_name = "reviewer/home.html"

    def get_context_data(self):
        c = super().get_context_data()
        my_reviews = Review.objects.filter(reviewer=self.request.user).all()
        for col, reviews in Review.in_kanban_columns(my_reviews).items():
            c[col.name] = reviews
        return c

class ShowManuscript(ReviewerMixin, DetailView):
    """Redirects to show the manuscript's last revision.
    """
    model = Manuscript

    def get_queryset(self):
        return Manuscript.objects.filter(reviewers=self.request.user)

    def get(self, request, *args, **kwargs):
        m = self.get_object()
        return redirect('reviewer:show_revision', m.id, m.revisions.last().revision_number)

class ShowRevision(ReviewerMixin, ManuscriptRevisionMixin, RevisionReviewMixin, DetailView):
    """Implements the main tab for a revision.
    """
    model = Revision
    template_name = "reviewer/manuscript_revision_detail.html"

class ShowReviews(ReviewerMixin, ManuscriptRevisionMixin, DetailView):
    """Implements the reviews tab."""
    template_name = "reviewer/reviews_detail.html"

class ShowReview(ReviewerMixin, ManuscriptRevisionMixin, RevisionReviewMixin, DetailView):
    """Implements the review tab."""
    template_name = "reviewer/review_detail.html"

    def get(self, request, *args, **kwargs):
        review = self.get_review()
        if review.revision.status == Revision.StatusChoices.PENDING and not review.text:
            m_id = self.get_revision().manuscript_id
            return redirect('reviewer:edit_review', m_id, self.get_revision().revision_number)
        else:
            return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        "Handles POST actions"
        review = self.get_review()
        sm = ReviewStateMachine(request)
        action = request.POST['action'].upper()
        if action == "SUBMIT":
            try:
                sm.transition(review, sm.states.SUBMITTED)
            except sm.IllegalTransition:
                return self.forbid_action("submit")
        else:
            return self.forbid_action(action)
        m_id = self.get_revision().manuscript_id
        return redirect('reviewer:show_review', m_id, self.get_revision().revision_number)

    def forbid_action(self, action):
        msg = "Action '{}' is not allowed.".format(action)
        messages.add_message(self.request, messages.WARNING, msg)
        return HttpResponseForbidden(msg)
        
class ReviewInstructions(ReviewerMixin, ManuscriptRevisionMixin, RevisionReviewMixin, TemplateView):
    """Implements the review instructions tab."""
    template_name = "reviewer/review_instructions.html"

class EditReview(ReviewerMixin, ManuscriptRevisionMixin, RevisionReviewMixin, UpdateView):
    """Implements the review-authoring tab for a revision.
    """
    model = Review
    form_class = EditReviewForm
    template_name = "reviewer/edit_review.html"

    def get_object(self):
        if self.get_revision().status != Revision.StatusChoices.PENDING:
            raise Http404()
        return self.get_review()

    def get_revision(self):
        try:
            return self.get_queryset().get(
                manuscript__id=self.kwargs['manuscript_pk'],
                revision_number=self.kwargs['revision_number']
            )
        except Revision.DoesNotExist:
            raise Http404("No such revision")

    def get_success_url(self):
        revision = self.get_revision()
        return reverse('reviewer:show_review', args=(revision.manuscript_id, revision.revision_number))

reviewer/templates/reviewer/partials/instructions.html
<h1>Writing a review</h1>

<p class="explanation">
Peer-review is a central mechanism by which communities of academic research
define quality and support their members in achieving that quality in their work. 
Researchers often put substantial effort into peer review even though it is
uncompensated and unacknowledge labor. Their motivation is to support the growth
of other scholars and to guide the priorities of their research communities. 
As a means of bootstrapping our community, standards for peer review are 
initially provided (below). But as our community matures, we will refine our values
and revise our standards for peer review. 
</p>
<p class="explanation">
</p>

<h2>Review guidelines</h2>
<p>
Reviews should be about one paragraph in length and they
should not take longer than 30 minutes to write (maybe a little longer the first
time). Sometimes it helps to have a 
quick read-through of a manuscript under review and then to go through again more 
carefully while writing the review. Within the one paragraph of your review, 
please do the following:</p>
<ul>
<li>In one sentence, <span class="bold">summarize the main point</span> of the
manuscript. Identify what genre the 
submission falls into (e.g. commentary, research proposal, reflection, or
special issue).</li>
<li><span class="bold">Explain what's working for you</span> in the manuscript. Where does it feel
relevant and connected to ideas we have been discussing? Where does the writing
feel clear? Where can you hear the author's voice? What's exciting?</li>
<li><span class="bold">Explain what's not working for you</span> yet. You don't need to critique the
manuscript sentence by sentence. Rather, try to summarize while giving specific
examples. For example, you might write, "The paragraphs sometimes feel
disconnected. Paragraph 2 ends by suggesting that we should replace teachers
with robots; I was surprised when Paragraph 3 began by arguing about who makes
the best pizza in Buffalo."
<li>If you are recommending major revisions, suggest how the authors might get
started. For example, if you found the manuscript biased and one-sided, suggest
an argument (or even a reference) which the authors might want to consider.</li>
</ul>

<h2>Making a recommendation</h2>
<p>In addition to your written review, you are asked to recommend a decision for
the manuscript. In making a recommendation, consider whether you
feel the manuscript is of high quality and ought to be read and discussed by the
class. The options available are:</p>
<ul>
<li><span class="bold">Accept</span>: The manuscript should be published in its current state.</li>
<li><span class="bold">Minor revisions</span>: The manuscript should be published, but it needs some
touch-ups. These might be grammatical, stylistic, or related to the content. For
example, you might suggest minor revisions because you would like to invite the
author to consider another perspective in one of their claims.</li>
<li><span class="bold">Major revisions</span>: The manuscript is promising, but
it needs substantial reworking. If you find the manuscript confusing and hard to
follow, consider which parts of the U-shaped structure of arguement it might be
missing. Here, your written review is particularly
important in suggesting the direction for revision. Keep in mind that some
authors may choose not to revise a manuscript if their reviewers feel it needs a
large amount of revision.</li>
<li><span class="bold">Reject</span>: A rejected manuscript won't be published by the journal and can't be
resubmitted. While rejections are common in prestigious journals, they will be
very rare or nonexistent in this journal :)</li>
</ul>
<p>
The journal editor reads all the reviews and makes a final decision on a
manuscript. If the editor feels a review is unhelpful or unsupportive, he may
request that the reviewer update the review. Should you receive a review which
you find hurtful or offensive, please contact the editor. We need to support
each others' growth, but we also need to be gentle in our feedback. 
</p>
<p>
You will remain a reviewer for a manuscript through its entire lifecycle. So if
a manuscript is returned for major revisions, you will be asked to review again 
when the author(s) resubmit a new version. If a manuscript has sufficiently
minor revisions, the editor may decide to accept a revision without sending it
again to reviewers. Some manuscripts may go through several iterations of
reviews.
</p>

<h2>Reviewing instructions for Special Issue 1: Formations</h2>
<p>
The first special issue of the journal solicited open-ended, narrative
manuscripts focused on "your own journey into graduate school and your
relationship with ideas which inspire you or those which oppress you."
In reviewing these submissions, keep in mind that diverse identities and
experiences may be best represented by unconventional structure and voice. 
Your focus as a reviewer should be on trying to understand what the manuscript
is trying to be (and giving feedback aimed at helping it best achieve its aim) 
rather than suggesting it should be something else. 
</p>

reviewer/templates/reviewer/partials/manuscript_revision_detail.html
<div id="manuscript-layout">
  <div class="manuscript-sidebar">
  {% block sidebar %}
    {% with current_revision=revision %}
      {% for revision in manuscript.revisions.all %}
        {% include "reviewer/partials/revision_summary.html" %}
      {% endfor %}
    {% endwith %}
  {% endblock %}
  </div>
  <div class="manuscript-content">
    <div class="manuscript-header">
      {% block manuscript_header %}
      <h1>{{revision.title}}</h1>
      <div class="manuscript-actions">
        {% block manuscript_actions %}
        {% endblock %}
      </div>
      {% endblock %}
    </div>
    {% block manuscript_divider %}
    <hr>
    {% endblock %}
    <div class="manuscript-text">
      {% block manuscript_text %}
        {{revision.text|safe}}
      {% endblock %}
    </div>
  </div>
</div>

reviewer/templates/reviewer/partials/review_cell.html
<article class="process-chart-cell review-{{review.status.lower}}">
  <p class="title">
    <a href="{% url 'reviewer:show_manuscript' review.revision.manuscript.id %}">{{review.revision.title}}</a></p>
    {% if review.kanban_column.name == "ASSIGNED" %}
      <p>Due {{review.date_due}}</p>
    {% elif review.status == "NOT_NEEDED" %}
      <p>No review needed; the editor issued a decision before your review was due.</p>
    {% elif review.status == "WITHDRAWN" %}
      <p>No review needed; the author withdrew their manuscript.</p>
    {% else %}
      <p>Submitted {{review.date_submitted}}</p>
    {% endif %}
	<p class="review-status">{{review.status}}</p>
</article>

reviewer/templates/reviewer/partials/review_summary.html
<article class="review">
	<p>Review of {{review.revision.title}}</p>
	<p>Due {{review.date_due}}</p>
	<p class="review-status">{{review.status}}</p>
</article>

reviewer/templates/reviewer/partials/revision_summary.html
<article class="revision {% if current_revision == revision %}current{% endif %}">
	<h3>
		{% if current_revision == revision %}
		  {{revision.title}} (Revision {{revision.revision_number}})
		{% else %}
		<a href="{% url 'reviewer:show_revision' revision.manuscript_id revision.revision_number %}">
			{{revision.title}}
		  (Revision {{revision.revision_number}})
		</a> 
		{% endif %}
	</h3>
	<p>{{revision.status_message_for_reviewers}}</p>
</article>

reviewer/templates/reviewer/partials/revision_tabs.html
<div class="manuscript-revision-tabs">
  {% if current_tab == "text" %}
    <div class="tab current">
      Text
    </div>
  {% else %}
    <div class="tab">
      <a href="{% url 'reviewer:show_revision' manuscript.pk revision.revision_number %}">Text</a>
    </div>
  {% endif %}
  {% if current_tab == "review" %}
    <div class="tab current">
      Review
    </div>
  {% else %}
    <div class="tab">
      <a href="{% url 'reviewer:show_review' manuscript.pk revision.revision_number %}">Review</a>
    </div>
  {% endif %}
  {% if current_tab == "instructions" %}
    <div class="tab current">
      Instructions
    </div>
  {% else %}
    <div class="tab">
      <a href="{% url 'reviewer:review_instructions' manuscript.pk revision.revision_number %}">Instructions</a>
    </div>
  {% endif %}
</div>

reviewer/templates/reviewer/partials/submenu.html
<nav id="submenu">
	<div class="menu-left">
		<div class="menu-item"><a href="{% url 'reviewer:home' %}">Your reviews</a></div>
	</div>
</nav>