author/urls.py
from django.urls import path

from . import views

app_name = "author"
urlpatterns = [
    path('', views.AuthorHome.as_view(), name='home'),
    path('instructions', views.AuthorInstructions.as_view(), name='instructions'),
    path('manuscripts/new', views.NewManuscript.as_view(), name='new_manuscript'),
    path('manuscripts/<int:pk>', views.ShowManuscript.as_view(), name='show_manuscript'),
    path('manuscripts/<int:manuscript_pk>/versions/<int:revision_number>', 
            views.ShowRevision.as_view(), name='show_revision'),
    path('manuscripts/<int:manuscript_pk>/versions/<int:revision_number>/reviews', 
            views.ShowRevisionReviews.as_view(), name='show_revision_reviews'),
    path('manuscripts/<int:manuscript_pk>/versions/<int:revision_number>/edit', 
            views.EditRevision.as_view(), name='edit_revision'),
]

cognitive_apprenticeship/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('public.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('author/', include('author.urls')),
    path('reviewer/', include('reviewer.urls')),
    path('editor/', include('editor.urls')),
    path('profile/', include('roles.urls')),
    path('test/', include('common.urls')),
]

common/urls.py
from django.urls import path

from . import views

app_name = "common"
urlpatterns = [
    path('email/<int:index>', views.TestEmail.as_view(), name='test_email'),
]

editor/urls.py
from django.urls import path

from . import views

app_name = "editor"
urlpatterns = [
    path('', views.EditorHome.as_view(), name='home'),
    path('manuscripts', views.ListManuscripts.as_view(), name='list_manuscripts'),
    path('manuscripts/<int:pk>', views.ShowManuscript.as_view(), name='show_manuscript'),
    path('manuscripts/<int:pk>/reviews', views.ShowManuscriptReviews.as_view(), name='show_manuscript_reviews'),
    path('manuscripts/<int:manuscript_pk>/versions/<int:revision_number>', 
            views.ShowRevision.as_view(), name='show_revision'),
    path('manuscripts/<int:manuscript_pk>/versions/<int:revision_number>/reviews', 
            views.ShowRevisionReviews.as_view(), name='show_revision_reviews'),
    path('manuscripts/<int:manuscript_pk>/versions/<int:revision_number>/reviews/editorial', 
            views.EditRevisionEditorialReview.as_view(), name='edit_revision_editorial_review'),
    path('reviews', views.ListReviews.as_view(), name='list_reviews'),
    path('issues', views.ListIssues.as_view(), name='list_issues'),
    path('issues/new', views.NewIssue.as_view(), name='new_issue'),
    path('issues/<int:pk>', views.ShowIssue.as_view(), name='show_issue'),
    path('issues/<int:pk>/edit', views.EditIssue.as_view(), name='edit_issue'),
]

reviewer/urls.py
from django.urls import path

from . import views

app_name = "reviewer"
urlpatterns = [
    path('', views.ReviewerHome.as_view(), name='home'),
    path('manuscripts/<int:pk>', views.ShowManuscript.as_view(), name='show_manuscript'),
    path('manuscripts/<int:manuscript_pk>/versions/<int:revision_number>', 
            views.ShowRevision.as_view(), name='show_revision'),
    path('manuscripts/<int:manuscript_pk>/versions/<int:revision_number>/reviews', 
            views.ShowReviews.as_view(), name='show_reviews'),
    path('manuscripts/<int:manuscript_pk>/versions/<int:revision_number>/review', 
            views.ShowReview.as_view(), name='show_review'),
    path('manuscripts/<int:manuscript_pk>/versions/<int:revision_number>/review/instructions', 
            views.ReviewInstructions.as_view(), name='review_instructions'),
    path('manuscripts/<int:manuscript_pk>/versions/<int:revision_number>/review/edit', 
            views.EditReview.as_view(), name='edit_review'),
]

roles/urls.py
from django.urls import path
from roles import views

app_name = "roles"
urlpatterns = [
    path('edit', views.EditProfile.as_view(), name="edit"),
    path('password', views.ChangePassword.as_view(), name="password"),
    path('', views.ShowProfile.as_view(), name="detail"),
]

common/models.py
from django.db import models

class NondeletedManager(models.Manager):
    "A model manager which excludes deleted objects"
    def get_queryset(self):
        return super().get_queryset().filter(deleted=False)

common/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.conf import settings
from common.email import send_journal_email

class TestEmail(TemplateView):
    template_name = "common/email_test.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['index'] = self.kwargs['index']
        return context

    def get(self, *args, **kwargs):
        index = self.kwargs['index']
        send_journal_email(
            f"Email test {index}",
            f"This is a test.",
            [addr for name, addr in settings.ADMINS]
        )
        return super().get(*args, **kwargs)

common/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="{% static 'base/style.css' %}">
    <link rel="stylesheet" href="{% static 'base/menu.css' %}">
    {% block head %}
    {% endblock %}
  </head>
  <body>
  <div id="page-wrapper">
    {% block menu %}
      {% include "menu.html" %}
    {% endblock %}
    {% block submenu %}
    {% endblock %}
    <div id="main-content">
      {% if messages %}
        {% for message in messages %}
        <div class="message {% if message.tags %}{{ message.tags }}{% endif %}">
	  {{message}}
	</div>
        {% endfor %}
      {% endif %}
      {% block content %}
      {% endblock %}
    </div>
  {% include "footer.html" %}
  </body>
</html>

common/templates/footer.html
<div id="footer">
	<div class="footer-item">
		<a href="https://chrisproctor.net">Chris Proctor</a>
	</div>
</div>

common/templates/menu.html
{% load settings %}
{% settings_value "SITE_FROZEN" as SITE_FROZEN %}
<nav id="menu">
	<div class="menu-left">
		<div class="menu-item clickable{% if menu_section == 'public' %} current{% endif %}">
      <a href="{% url 'public:home_page' %}">Home</a>
    </div>
      {% if not SITE_FROZEN %}
		{% if user.is_authenticated %}
		  {% if user.profile.is_author %}
		    <div class="menu-item  clickable{% if menu_section == 'author' %} current{% endif %}">
          <a href="{% url 'author:home' %}">Author</a>
        </div>
			{% endif %}
		  {% if user.profile.is_reviewer %}
      <div class="menu-item clickable{% if menu_section == 'reviewer' %} current{% endif %}">
        <a href="{% url 'reviewer:home' %}">Reviewer</a>
      </div>
			{% endif %}
		  {% if user.profile.is_editor %}
		    <div class="menu-item clickable{% if menu_section == 'editor' %} current{% endif %}">
          <a href="{% url 'editor:home' %}">Editor</a>
        </div>
			{% endif %}
		  {% if user.is_superuser %}
		    <div class="menu-item clickable">
          <a href="{% url 'admin:index' %}">Admin</a>
        </div>
			{% endif %}
		{% endif %}
	</div>
	<div class="menu-right">
		{% if user.is_authenticated %}
        <div class="menu-item clickable{% if menu_section == 'profile' %} current{% endif %}">
              <a href="{% url 'roles:detail' %}">{{user.username}}</a>
          </div>
		  <div class="menu-item clickable"><a href="{% url 'logout' %}">Log out</a></div>
		{% else %}
		  <div class="menu-item clickable"><a href="{% url 'login' %}">Log in</a></div>
		{% endif %}
	  {% endif %}
	</div>
</nav>