cognitive_apprenticeship/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('public.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('author/', include('author.urls')),
    path('reviewer/', include('reviewer.urls')),
    path('editor/', include('editor.urls')),
    path('profile/', include('roles.urls')),
    path('test/', include('common.urls')),
]

editor/urls.py
from django.urls import path

from . import views

app_name = "editor"
urlpatterns = [
    path('', views.EditorHome.as_view(), name='home'),
    path('manuscripts', views.ListManuscripts.as_view(), name='list_manuscripts'),
    path('manuscripts/<int:pk>', views.ShowManuscript.as_view(), name='show_manuscript'),
    path('manuscripts/<int:pk>/reviews', views.ShowManuscriptReviews.as_view(), name='show_manuscript_reviews'),
    path('manuscripts/<int:manuscript_pk>/versions/<int:revision_number>', 
            views.ShowRevision.as_view(), name='show_revision'),
    path('manuscripts/<int:manuscript_pk>/versions/<int:revision_number>/reviews', 
            views.ShowRevisionReviews.as_view(), name='show_revision_reviews'),
    path('manuscripts/<int:manuscript_pk>/versions/<int:revision_number>/reviews/editorial', 
            views.EditRevisionEditorialReview.as_view(), name='edit_revision_editorial_review'),
    path('reviews', views.ListReviews.as_view(), name='list_reviews'),
    path('issues', views.ListIssues.as_view(), name='list_issues'),
    path('issues/new', views.NewIssue.as_view(), name='new_issue'),
    path('issues/<int:pk>', views.ShowIssue.as_view(), name='show_issue'),
    path('issues/<int:pk>/edit', views.EditIssue.as_view(), name='edit_issue'),
]

roles/urls.py
from django.urls import path
from roles import views

app_name = "roles"
urlpatterns = [
    path('edit', views.EditProfile.as_view(), name="edit"),
    path('password', views.ChangePassword.as_view(), name="password"),
    path('', views.ShowProfile.as_view(), name="detail"),
]

editor/models.py
from django.db import models

class JournalIssue(models.Model):
    title = models.CharField(max_length=200)
    volume = models.IntegerField()
    number = models.IntegerField()
    introduction = models.TextField()
    date_published = models.DateTimeField(blank=True, null=True)
    manuscripts = models.ManyToManyField('author.Manuscript', related_name='issues', blank=True)
    published = models.BooleanField(default=False, blank=True)

    def __str__(self):
        return "{} (Vol {}, Number {})".format(self.title, self.volume, self.number)

    class Meta:
        ordering = ('-volume', '-number')

editor/forms.py
from django import forms
from django.contrib.auth.models import User
from author.models import Manuscript, Revision
from reviewer.models import Review
from tinymce.widgets import TinyMCE
from .models import JournalIssue

class AssignReviewerForm(forms.Form):
    """A form for adding a User as a reviewer.
    """
    reviewer = forms.ModelChoiceField(queryset=None, required=True)

    def __init__(self, manuscript, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.possible_reviewers = (
            User.objects
            .filter(profile__is_reviewer=True)
            .exclude(manuscripts=manuscript)
            .exclude(reviewed_manuscripts=manuscript)
        )
        self.fields['reviewer'].queryset = self.possible_reviewers

    def num_possible_reviewers(self):
        return bool(len(self.possible_reviewers))

class NewJournalIssueForm(forms.ModelForm):
    
    introduction = forms.CharField(widget=TinyMCE()) 

    class Meta:
        model = JournalIssue
        fields = ['title', 'introduction', 'volume', 'number']

class EditJournalIssueForm(forms.ModelForm):

    introduction = forms.CharField(widget=TinyMCE()) 
    
    manuscripts = forms.ModelMultipleChoiceField(
        queryset=Manuscript.objects.filter(revisions__status__in=[
            Revision.StatusChoices.ACCEPT, 
            Revision.StatusChoices.PUBLISHED,
        ]),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )

    class Meta:
        model = JournalIssue
        fields = ['title', 'introduction', 'volume', 'number', 'published', 'manuscripts']

class EditorialReviewForm(forms.ModelForm):
    editorial_review = forms.CharField(widget=TinyMCE())

    class Meta:
        model = Revision
        fields = ['editorial_review']

class EditorialDecisionForm(forms.ModelForm):
    """Allows the editor to issue a decision. 
    Uses Review.recommendation for convenience.
    """
    class Meta:
        model = Review
        fields = ['recommendation']

editor/views.py
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, FormView
from django.contrib import messages
from django.shortcuts import redirect
from django.urls import reverse
from django.conf import settings
from author.models import Manuscript, Revision
from author.mixins import ManuscriptRevisionMixin
from author.state_machine import RevisionStateMachine
from reviewer.models import Review
from reviewer.forms import EditReviewForm
from editor.forms import (
    AssignReviewerForm, 
    EditorialReviewForm,
    EditorialDecisionForm
)
from .models import JournalIssue
from .forms import NewJournalIssueForm, EditJournalIssueForm
from reviewer.email import notify_user_when_review_created

class EditorRoleRequiredMixin:
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            msg = "You must be logged in to view editor pages."
            messages.add_message(request, messages.WARNING, msg)
            return redirect('public:home_page')
        if not request.user.profile.is_editor:
            msg = "You are not registered as an editor."
            messages.add_message(request, messages.WARNING, msg)
            return redirect('public:home_page')
        return super().dispatch(request, *args, **kwargs)

class EditorHome(EditorRoleRequiredMixin, TemplateView):
    def get(self, request, *args, **kwargs):
        return redirect('editor:list_manuscripts')

class ListManuscripts(EditorRoleRequiredMixin, TemplateView):
    template_name = "editor/list_manuscripts.html"

    def get_context_data(self, **kwargs):
        c = super().get_context_data(**kwargs)
        qs = Manuscript.objects
        if 'q' in self.request.GET and self.request.GET['q']:
            qs = qs.filter(authors__username=self.request.GET['q'])
        qs = qs.count_reviews('num_reviews')
        qs = qs.count_reviews('num_complete_reviews', status=Review.StatusChoices.COMPLETE)
        for col, manuscripts in Manuscript.in_kanban_columns(qs.all()).items():
            c[col.name] = manuscripts
        return c
        
class ShowManuscript(EditorRoleRequiredMixin, DetailView):
    model = Manuscript

    def get(self, request, *args, **kwargs):
        m = self.get_object()
        return redirect('editor:show_revision', m.id, m.revisions.last().revision_number)

class ShowManuscriptReviews(EditorRoleRequiredMixin, DetailView):
    model = Manuscript

    def get(self, request, *args, **kwargs):
        m = self.get_object()
        return redirect('editor:show_revision_reviews', m.id, m.revisions.last().revision_number)

class ShowRevision(EditorRoleRequiredMixin, ManuscriptRevisionMixin, DetailView):
    model = Revision
    template_name = 'editor/manuscript_revision_detail.html'
    http_method_names = ['get', 'post']

    def __init__(self, *args, **kwargs):
        super(*args, **kwargs)
        self.object = None

    def get_context_data(self, **kwargs):
        c = super().get_context_data(**kwargs)
        revision = self.get_object()
        m = revision.manuscript
        missing_authorships = m.authorships.filter(acknowledged=False).all()
        missing_authors = [authorship.author for authorship in missing_authorships]
        c['is_waiting_for_authors'] = (len(missing_authors) > 0)
        if len(missing_authors) > 0:
            msg = "Waiting on authorship acknowledgement: {}"
            c['missing_authors_message'] = msg.format(m.format_names(missing_authors))
        return c

class ShowRevisionReviews(EditorRoleRequiredMixin, ManuscriptRevisionMixin, DetailView):
    model = Revision
    template_name = 'editor/revision_reviews_detail.html'

    def get_context_data(self, **kwargs):
        c = super().get_context_data(**kwargs)
        c['decision_form'] = EditorialDecisionForm()
        return c

    def post(self, request, *args, **kwargs):
        "Handles the editorial decision form"
        action = request.POST['action'].upper()
        revision = self.get_revision()
        if action.upper() == "ISSUE DECISION":
            if revision.status != Revision.StatusChoices.PENDING:
                return self.invalid_post("Only pending revisions can have decisions applied.")
            sm = RevisionStateMachine(request)
            decision = request.POST['recommendation'].upper()
            if decision == "ACCEPT": 
                sm.transition(revision, sm.states.ACCEPT)
            elif decision == "MINOR":
                sm.transition(revision, sm.states.MINOR_REVISION)
            elif decision == "MAJOR":
                sm.transition(revision, sm.states.MAJOR_REVISION)
            elif decision == "REJECT":
                sm.transition(revision, sm.states.REJECT)
            else:
                return self.invalid_post("Invalid decision '{}'".format(request.POST['recommendation']))
            return redirect('editor:show_revision_reviews', revision.manuscript_id, revision.revision_number)
        else:
            return self.invalid_post("Invalid action '{}'".format(action))

    def invalid_post(self, message):
        revision = self.get_revision()
        messages.add_message(self.request, messages.WARNING, message)
        return redirect('editor:show_revision_reviews', revision.manuscript_id, revision.revision_number)

class EditRevisionEditorialReview(EditorRoleRequiredMixin, ManuscriptRevisionMixin, UpdateView):
    model = Revision
    template_name = 'editor/edit_revision_editorial_review.html'
    form_class = EditorialReviewForm

    def get_success_url(self):
        r = self.get_object()
        return reverse('editor:show_revision_reviews', args=(r.manuscript_id, r.revision_number))

class ListReviews(EditorRoleRequiredMixin, TemplateView):
    template_name = "editor/list_reviews.html"

    def get_context_data(self, **kwargs):
        c = super().get_context_data(**kwargs)
        qs = Review.objects
        if 'q' in self.request.GET and self.request.GET['q']:
            qs = qs.filter(reviewer__username=self.request.GET['q'])
        for col, reviews in Review.in_kanban_columns(qs.all()).items():
            c[col.name] = reviews
        return c
       
class ListIssues(EditorRoleRequiredMixin, ListView):
    model = JournalIssue
    template_name = "editor/list_issues.html"
    context_object_name = "issues"

class ShowIssue(EditorRoleRequiredMixin, DetailView):
    model = JournalIssue
    template_name = "editor/issue_detail.html"
    context_object_name = "issue"

class NewIssue(EditorRoleRequiredMixin, CreateView):
    model = JournalIssue
    form_class = NewJournalIssueForm
    template_name = "editor/new_issue.html"

    def get_success_url(self):
        return reverse('editor:show_issue', args=(self.object.id,))

class EditIssue(EditorRoleRequiredMixin, UpdateView):
    model = JournalIssue
    form_class = EditJournalIssueForm
    template_name = "editor/edit_issue.html"
    context_object_name = "issue"

    def post(self, request, *args, **kwargs):
        result = super().post(request, *args, **kwargs)
        sm = RevisionStateMachine(request)
        for manuscript in self.get_object().manuscripts.all():
            revision = manuscript.revisions.last()
            if revision.status == Revision.StatusChoices.ACCEPT:
                sm.transition(revision, sm.states.PUBLISHED)
        return result
    
    def get_success_url(self):
        return reverse('editor:show_issue', args=(self.object.id,))

editor/templates/editor/base.html
{% extends "base.html" %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'editor_style.css' %}">
{% endblock %}

{% block menu %}
  {% with menu_section="editor" %}
    {% include "menu.html" %}
  {% endwith %}
{% endblock %}

{% block submenu %}
  {% include "editor/partials/submenu.html" %}
{% endblock %}

editor/templates/editor/edit_issue.html
{% extends "editor/base.html" %}

{% block head %}
  {{ form.media }}
{% endblock %}

{% block content %}
<h1>Edit {{issue.title}}</h1>
<form method="post" action="{% url 'editor:edit_issue' issue.id %}">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Update">
</form>
{% endblock %}

editor/templates/editor/edit_revision_editorial_review.html
{% extends "editor/revision_reviews_detail.html" %}

{% block head %}
  {{ form.media }}
{% endblock %}

{% block editorial_review %}
<form method="post" action="{% url 'editor:edit_revision_editorial_review' manuscript.id revision.revision_number %}">
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="Save">
</form>
{% endblock %}

editor/templates/editor/home.html
{% extends "editor/base.html" %}

{% block content %}
<h1>Editor</h1>

{% endblock %}

editor/templates/editor/issue_detail.html
{% extends "editor/base.html" %}

{% block content %}
  <h1>{{issue.title}}</h1>
  <p><a href="{% url 'editor:edit_issue' issue.id %}">Edit</a></p>
  {% if issue.published %}
   <p>Published</p>
  {% else %}
   <p>Not published</p>
  {% endif %}
  <p>Volume {{issue.volume}}, number {{issue.number}}</p>
  <p>{{issue.introduction|safe}}</p>
  {% if issue.manuscripts.count %}
    <h2>Contents</h2>
    <ul>
      {% for m in issue.manuscripts.all %}
        <li>{{m}}</li>
      {% endfor %}
    </ul>
  {% endif %}
{% endblock %}

editor/templates/editor/list_issues.html
{% extends "editor/base.html" %}

{% block content %}
<div id="main-content-container">
<h1>Issues</h1>
<ul>
  {% for issue in issues %}
    <li>
      <a href="{% url 'editor:show_issue' issue.id %}">{{issue.title}}</a> 
      (Vol {{issue.volume}}, Number {{issue.number}})
      <ul>
        {% for m in issue.manuscripts.all %}
          <li>
            {{m}}
          </li>
        {% endfor %}
      </ul>
    </li>
  {% endfor %}
  <li><a href="{% url 'editor:new_issue' %}">Create new issue</a></li>
</ul>
</div>
{% endblock %}

editor/templates/editor/list_manuscripts.html
{% extends "editor/base.html" %}

{% block content %}
<div id="main-content-container">
<h1>Manuscripts</h1>
<form method="get" action="{% url 'editor:list_manuscripts' %}">
  <input type="text" name="q">
  <input type="submit" value="Search by author username">
</form>
<hr>
<div class="process-chart">
	<div class="process-chart-col">
		<div class="process-chart-cell cell-header">Unsubmitted</div>
		{% for manuscript in IN_PREPARATION %}
		  {% include "editor/partials/manuscript_cell.html" %}
		{% endfor %}
	</div><div class="process-chart-col">
		<div class="process-chart-cell cell-header">Pending</div>
		{% for manuscript in IN_SUBMISSION %}
		  {% include "editor/partials/manuscript_cell.html" %}
		{% endfor %}
	</div><div class="process-chart-col">
		<div class="process-chart-cell cell-header">Decided</div>
		{% for manuscript in DECIDED %}
		  {% include "editor/partials/manuscript_cell.html" %}
		{% endfor %}
	</div><div class="process-chart-col">
		<div class="process-chart-cell cell-header">Published</div>
		{% for manuscript in PUBLISHED %}
		  {% include "editor/partials/manuscript_cell.html" %}
		{% endfor %}
	</div>
</div>
</div>
{% endblock %}

editor/templates/editor/list_reviews.html
{% extends "editor/base.html" %}

{% block content %}
<div id="main-content-container">
<h1>Reviews</h1>
<form method="get" action="{% url 'editor:list_reviews' %}">
  <input type="text" name="q">
  <input type="submit" value="Search by reviewer username">
</form>
<hr>
<div class="process-chart">
	<div class="process-chart-col">
		<div class="process-chart-cell cell-header">Assigned</div>
		{% for review in ASSIGNED %}
		  {% include "editor/partials/review_cell.html" %}
		{% endfor %}
	</div>
    <div class="process-chart-col">
		<div class="process-chart-cell cell-header">Submitted</div>
		{% for review in SUBMITTED %}
		  {% include "editor/partials/review_cell.html" %}
		{% endfor %}
	</div>
    <div class="process-chart-col">
		<div class="process-chart-cell cell-header">Complete</div>
		{% for review in COMPLETE %}
		  {% include "editor/partials/review_cell.html" %}
		{% endfor %}
	</div>
</div>
</div>
{% endblock %}

editor/templates/editor/manuscript_cell.html
<article class="process-chart-cell {{manuscript.revisions.last.status}}">
  <p class="title">
     <a href="{% url 'editor:show_manuscript' manuscript.id %}">{{manuscript.short_title}}</a>
  </p>
  <p>{{manuscript.author_names}}</p>
	<p>{{manuscript.status_message}}</p>
	<p>
		{% if manuscript.num_reviews %}
			{{manuscript.num_complete_reviews}}/{{manuscript.num_reviews}} reviews complete.
		{% else %}
			No reviewers assigned.
		{% endif %}
	</p>
</article>

editor/templates/editor/manuscript_revision.html
{% extends "editor/base.html" %}

{% block content %}
<div id="manuscript-layout">
  <div class="manuscript-sidebar">
  {% block sidebar %}
    {% with current_revision=revision %}
      {% for revision in manuscript.revisions.all %}
        {% include "editor/partials/revision_summary.html" %}
      {% endfor %}
    {% endwith %}
  {% endblock %}
  </div>
  <div class="manuscript-content">
    {% block manuscript_content %}
    <div class="manuscript-header">
      {% block manuscript_header %}
      <h1>{{revision.title}}</h1>
      <p>by {{manuscript.author_names}}</p>
      {% if is_waiting_for_authors %}
        <p>{{missing_authors_message}}</p>
      {% endif %}
      <p> {{revision.status}}</p>
      <div class="manuscript-actions">
        {% block manuscript_actions %}
        {% endblock %}
      </div>
      {% endblock %}
    </div>
    {% block manuscript_divider %}
    <div class="manuscript-revision-tabs">
      <div class="tab current">
        Text
      </div>
    </div>
    {% endblock %}
    <div class="manuscript-text">
      {% block manuscript_text %}
        {{revision.text|safe}}
      {% endblock %}
    </div>
    {% endblock %}
  </div>
</div>
{% endblock %}

editor/templates/editor/manuscript_revision_detail.html
{% extends "editor/manuscript_revision.html" %}

{% block manuscript_divider %}
  {% with current_tab="text" %}
    {% include "editor/partials/revision_tabs.html" %}
  {% endwith %}
{% endblock %}

{% block manuscript_text %}
  {% if revision.revision_note %}
    <h2>Revision note</h2>
    {{revision.revision_note|safe}}
    <hr>
    <h2>Revised manuscript</h2>
  {% endif %}
  {{revision.text|safe}}
{% endblock %}

editor/templates/editor/new_issue.html
{% extends "editor/base.html" %}

{% block head %}
  {{ form.media }}
{% endblock %}

{% block content %}
<h1>Create a new issue</h1>
<form method="post" action="{% url 'editor:new_issue' %}">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Submit">
</form>
{% endblock %}

editor/templates/editor/revision_reviews_detail.html
{% extends "editor/manuscript_revision.html" %}

{% block manuscript_divider %}
  {% with current_tab="reviews" %}
    {% include "editor/partials/revision_tabs.html" %}
  {% endwith %}
{% endblock %}

{% block manuscript_text %}
  {% block editorial_review %}
    <h2>Editorial review</h2>
    {% if revision.status == "PENDING" %}
      {% if revision.editorial_review %}
        {{revision.editorial_review|safe}}
        <a href="{% url 'editor:edit_revision_editorial_review' manuscript.id revision.revision_number %}">
          <button>Edit editorial review</button>
        </a>
        <form method="post" action="{% url 'editor:show_revision_reviews' manuscript.id revision.revision_number %}">
          {% csrf_token %}
          {{ decision_form }}
          <input type="submit" name="action" value="Issue decision">
        </form>
      {% else %}
        <p class="explanation">You need to add an editorial review before issuing a decision.</p>
        <a href="{% url 'editor:edit_revision_editorial_review' manuscript.id revision.revision_number %}">
          <button>Add editorial review</button>
        </a>
      {% endif %}
    {% else %}
      {{ revision.editorial_review|safe }}
    {% endif %}
  {% endblock %}
  {% for review in revision.reviews.all %}
    <hr>
    <h2>{{review.reviewer.first_name}} {{review.reviewer.last_name}}</h2>
    {% if review.status == "ASSIGNED" %}
      <p class="explanation">Review is due by {{review.date_due}}</p>
    {% elif review.status == "SUBMITTED" %}
      <p class="explanation">Recommendation: {{review.recommendation}}</p>
      {{review.text|safe}}
    {% elif review.status == "COMPLETE" %}
      <p class="explanation">Recommendation: {{review.recommendation}}</p>
      {{review.text|safe}}
    {% elif review.status == "EXPIRED" %}
      <p class="explanation">Review not submitted in time.</p>
    {% elif review.status == "WITHDRAWN" %}
      <p class="explanation">The revision was withdrawn.</p>
    {% elif review.status == "NOT_NEEDED" %}
      <p class="explanation">Editorial decision made before review was submitted.</p>
    {% elif review.status == "EDIT_REQUESTED" %}
      <p class="explanation">Editor requested edits to this review.</p>
      <p class="explanation">Recommendation: {{review.recommendation}}</p>
      {{review.text|safe}}
    {% endif %}
  {% endfor %}
{% endblock %}

editor/templates/editor/show_manuscript.html
{% extends "base.html" %}

{% block content %}
<h1>{{manuscript.revisions.last.title}}</h1>
<p>{{manuscript.author_names}}</p>
<p>{{manuscript.status_message}}</p>
<p>{{manuscript.revisions.count}} revisions</p>
<h2>Reviewers</h2>
{% if manuscript.reviewers.count %}
  <ul>
  {% for reviewer in manuscript.reviewers.all %}
    <li>
      {{reviewer}}
      <form method="post" action="{% url 'editor:show_manuscript' manuscript.id %}"> 
      {% csrf_token %}
      <input type="hidden" name="username" value="{{reviewer}}">
      <input type="hidden" name="action" value="remove_reviewer">
      <input type="submit" value="Remove">
  </form>
    </li>	
  {% endfor %}
  </ul>
{% else %}
<p>No reviewers are assigned to this manuscript</p>
{% endif %}
{% if manuscript.can_assign_reviewer %}
  {% if assign_reviewer_form.num_possible_reviewers %}
  <form method="post" action="{% url 'editor:show_manuscript' manuscript.id %}">
	{% csrf_token %}
	{{ assign_reviewer_form }}
	<input type="hidden" name="action" value="assign_reviewer">
	<input type="submit" value="Assign reviewer">
  </form>
  {% else %}
  <p>Can't assign additional reviewers; there are no eligible users.</p>
  {% endif %}
{% endif %}
<hr>
{{manuscript.revisions.last.text|safe}}
{% endblock%}